spring:
  application:
    name: inscritos
  datasource:
    url: jdbc:postgresql://localhost:5432/projects
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  api:
    security:
      secretKey: uidhsa7ehasdshse890w32489097ws342h0we290